# Generated by Django 5.2.3 on 2025-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_participant_email_alter_participant_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(),
        ),
    ]
