# Generated by Django 5.0.1 on 2025-07-18 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_category_name_alter_event_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="event_images/"),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="rsvped_events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
