# GENERATED BY TRANSFORMAR MODEL

import os
import django
import random
from faker import Faker

# Setup Django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "task_management.settings")
django.setup()

from events.models import Category, Event, Participant

fake = Faker()

# Clear old data
Category.objects.all().delete()
Event.objects.all().delete()
Participant.objects.all().delete()

# Create 50 Categories
categories = []
for _ in range(50):
    cat = Category.objects.create(
        name=fake.unique.word().capitalize(), description=fake.sentence()
    )
    categories.append(cat)

# Create 200 Events
events = []
for _ in range(200):
    date = fake.date_between(start_date="-30d", end_date="+30d")
    time = fake.time()
    event = Event.objects.create(
        name=fake.catch_phrase(),
        description=fake.paragraph(),
        date=date,
        time=time,
        location=fake.city(),
        category=random.choice(categories),
    )
    events.append(event)

# Create 600 Participants
for _ in range(600):
    participant = Participant.objects.create(
        name=fake.name(), email=fake.unique.email()
    )
    participant.events.set(random.sample(events, k=random.randint(1, 8)))

print(
    "✅ Database populated successfully with 50 categories, 200 events, and 600 participants!"
)
