# Generated by Django 5.2.3 on 2025-07-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("In Progress", "IN_PROGRESS"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
